#!/bin/sh

set -e

dist="trixie"

lb config noauto \
--color \
--archive-areas "main contrib non-free non-free-firmware" \
--distribution "$dist" \
--apt-indices false \
--apt-recommends false \
--debootstrap-options "--include=apt-transport-https,ca-certificates,openssl" \
--debconf-frontend noninteractive \
--updates true \
--backports true \
--source false \
--firmware-chroot false \
--debian-installer none \
--uefi-secure-boot enable \
--bootloaders "grub-pc grub-efi" \
--initramfs live-boot \
--chroot-squashfs-compression-type zstd \
--chroot-squashfs-compression-level 3 \
--win32-loader false \
"${@}"
